"""Native Params API; keep signatures aligned with params_pyx.pyx.

Values depend on the registered key's type. Known keys below narrow common
integration boundaries; arbitrary keys retain their runtime-dependent type.
"""
from enum import IntEnum, IntFlag
from collections.abc import Callable
from typing import Any, Literal, overload

class ParamKeyFlag(IntFlag):
  PERSISTENT = ...
  CLEAR_ON_MANAGER_START = ...
  CLEAR_ON_ONROAD_TRANSITION = ...
  CLEAR_ON_OFFROAD_TRANSITION = ...
  DEVELOPMENT_ONLY = ...
  CLEAR_ON_IGNITION_ON = ...
  BACKUP = ...
  ALL = ...

class ParamKeyType(IntEnum):
  STRING = ...
  BOOL = ...
  INT = ...
  FLOAT = ...
  TIME = ...
  JSON = ...
  BYTES = ...

class UnknownKeyName(Exception): ...

class Params:
  def __init__(self, d: str = "") -> None: ...
  def clear_all(self, tx_flag: ParamKeyFlag = ...) -> None: ...
  def check_key(self, key: str | bytes) -> bytes: ...
  @overload
  def get(self, key: Literal['CurrentRoute', 'BPLearnedStopsLatch'], block: bool = False, return_default: bool = False) -> str | None: ...
  @overload
  def get(self, key: Literal['IsOnroad'], block: bool = False, return_default: bool = False) -> bool | None: ...
  @overload
  def get(self, key: str | bytes, block: bool = False, return_default: bool = False) -> Any: ...
  def get_bool(self, key: str | bytes, block: bool = False) -> bool: ...
  def put(self, key: str | bytes, dat: Any, block: bool = False) -> None: ...
  def put_bool(self, key: str | bytes, val: bool, block: bool = False) -> None: ...
  def remove(self, key: str | bytes) -> None: ...
  def get_param_path(self, key: str | bytes = "") -> str: ...
  def get_type(self, key: str | bytes) -> ParamKeyType: ...
  def all_keys(self, flag: ParamKeyFlag = ...) -> list[bytes]: ...
  def get_default_value(self, key: str | bytes) -> Any: ...
  def cpp2python(self, key: str | bytes, value: Any) -> Any: ...
  def python2cpp(self, proposed_type: type, expected_type: ParamKeyType, value: Any, key: str | bytes) -> Any: ...

CPP_2_PYTHON: dict[ParamKeyType, Callable[[bytes], Any]]
PYTHON_2_CPP: dict[tuple[type, ParamKeyType], Callable[[Any], Any]]
